# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 517)
        MainWindow.setMinimumSize(QtCore.QSize(639, 517))
        MainWindow.setMaximumSize(QtCore.QSize(639, 517))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sputnik_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sputnik_btn.setGeometry(QtCore.QRect(310, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sputnik_btn.setFont(font)
        self.sputnik_btn.setObjectName("sputnik_btn")
        self.shema_btn = QtWidgets.QPushButton(self.centralwidget)
        self.shema_btn.setGeometry(QtCore.QRect(160, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shema_btn.setFont(font)
        self.shema_btn.setObjectName("shema_btn")
        self.gibrid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gibrid_btn.setGeometry(QtCore.QRect(460, 440, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gibrid_btn.setFont(font)
        self.gibrid_btn.setObjectName("gibrid_btn")
        self.find_line = QtWidgets.QLineEdit(self.centralwidget)
        self.find_line.setGeometry(QtCore.QRect(20, 400, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.find_line.setFont(font)
        self.find_line.setObjectName("find_line")
        self.find_btn = QtWidgets.QPushButton(self.centralwidget)
        self.find_btn.setGeometry(QtCore.QRect(20, 440, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.find_btn.setFont(font)
        self.find_btn.setObjectName("find_btn")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(20, 10, 601, 351))
        self.img.setObjectName("img")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 370, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sputnik_btn.setText(_translate("MainWindow", "Спутник"))
        self.shema_btn.setText(_translate("MainWindow", "Схема"))
        self.gibrid_btn.setText(_translate("MainWindow", "Гибрид"))
        self.find_btn.setText(_translate("MainWindow", "Поиск"))
        self.img.setText(_translate("MainWindow", "Изображение"))
        self.label.setText(_translate("MainWindow", "Введите адрес"))
